### PR TITLE
use native_toolchain_rust

### PR DESCRIPTION
**Pull request by knopp**

### CODE REVIEW

**Comment by knopp** [comment]
Not quite nice with the dependency override also not sure what exactly is going on with the huge lock file change.

**Comment by SaltySpaghetti** [comment]
I'm receiving this error trying to run `flutter pub get` inside the `ffi_rust_plugin` directory
```bash
Because every version of native_toolchain_rust from git depends on native_assets_cli from hosted and
  ffi_rust_plugin depends on native_assets_cli from git, native_toolchain_rust from git is forbidden.
So, because ffi_rust_plugin depends on native_toolchain_rust from git, version solving failed.
```

Am I missing something?

**Comment by knopp** [comment]
Yes, this will only work if you run `flutter pub get` in the top level directory.

**Comment by knopp** [comment]
To get this working for other directories I'd need to add the dependency override for `native_assets_cli` to more places, i think at least `ffi_rust_plugin/example`, but that one should probably be removed completely?

**Comment by SaltySpaghetti** [comment]
> To get this working for other directories I'd need to add the dependency override for `native_assets_cli` to more places, i think at least `ffi_rust_plugin/example`, but that one should probably be removed completely?

I use it to test the rust code standalone. I'd like to keep it

**Comment by knopp** [comment]
Yeah, my bad, I though the example was just the one generated by template. I added missing overrides. These can be removed once native_toolchain_cli gets published.

**Comment by SaltySpaghetti** [comment]
I still can't get `native_toolchain_rust` resolved.

That's my output running `flutter pub get`
```bash
Resolving dependencies... 
Downloading packages... 
  collection 1.18.0 (1.19.0 available)
  ffigen 9.0.1 (12.0.0 available)
  http_parser 4.0.2 (4.1.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
! native_assets_cli 0.6.1-wip from git https://github.com/dart-lang/native.git at 249d66 in pkgs/native_assets_cli (overridden)
  shelf 1.4.1 (1.4.2 available)
  test 1.25.7 (1.25.8 available)
  test_api 0.7.2 (0.7.3 available)
  test_core 0.6.4 (0.6.5 available)
Got dependencies!
8 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
```
I get no errors, but inside the rust hook I see this
image

**Comment by knopp** [comment]
I removed the unused import. Did you restart analyzer?

**Comment by SaltySpaghetti** [comment]
Yes, I've restarted the editor but the package it's missing

**Comment by SaltySpaghetti** [comment]
Seems like running `flutter pub get` inside `plugin/ffi_rust_plugin` solved the issue

**Pull request merged**
